<a href="https://colab.research.google.com/github/Priangshu-18/Matrix-basics/blob/main/Working_with_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
matrix_1 = np.array([[2,3],[6,7]])

In [ ]:
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_2 = np.array([[2,3],[6,7],[8,6]])
print(matrix_2)

[[2 3]
 [6 7]
 [8 6]]


In [ ]:
# Random Matrix
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.69786772 0.7782934  0.6766709 ]
 [0.24738588 0.2240557  0.55872986]
 [0.70705468 0.92210165 0.839918  ]]


In [ ]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[71  8 41  3 59]
 [54 70 96 60 50]
 [93 33 23 78 60]
 [49 36 86 68 47]]


In [3]:
# Matrix with all values as 1
ones_matrix = np.ones((5,5), dtype=int)
print(ones_matrix)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
# Matrix with all values as 0 (null matrix or zero matrix)
ones_matrix = np.zeros((3,3), dtype=int)
print(ones_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
# Identity matrix
ones_matrix = np.eye(3,3)
print(ones_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a matrix

In [11]:
a = np.random.randint(10, size=(3,3))
print(a)

[[7 5 4]
 [9 3 4]
 [1 8 7]]


In [12]:
transpose_of_a = np.transpose(a)

In [13]:
print(transpose_of_a)

[[7 9 1]
 [5 3 8]
 [4 4 7]]


# Matrix Addition and Subtraction

In [19]:
matrix_1 = np.array([[2,3],[6,7]])
matrix_2 = np.array([[2,4],[9,3]])

In [17]:
print(matrix_1)

[[2 3]
 [6 7]]


In [18]:
print(matrix_2)

[[2 4]
 [9 3]]


In [15]:
sum = matrix_1 + matrix_2
print(sum)

[[ 4  7]
 [15 10]]


In [21]:
sum = np.add(matrix_1, matrix_2)
print(sum)

[[ 4  7]
 [15 10]]


**Same goes for subtraction also**

In [23]:
difference = matrix_1 - matrix_2
print(difference)

[[ 0 -1]
 [-3  4]]


In [24]:
difference = np.subtract(matrix_1, matrix_2)
print(difference)

[[ 0 -1]
 [-3  4]]


# Matrix Multiplication

In [25]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[9 1 5 2]
 [9 0 0 8]
 [0 8 4 0]
 [8 8 0 2]]


In [26]:
product = np.multiply(x,y)
print(product)

[[45  5 25 10]
 [45  0  0 40]
 [ 0 40 20  0]
 [40 40  0 10]]


**Multiplying two Matrices**

In [31]:
a = np.random.randint(10, size=(3,3))
b = np.random.randint(20, size=(3,4))

In [32]:
print(a)

[[6 3 4]
 [6 2 2]
 [3 4 8]]


In [33]:
print(b)

[[14  4  0 16]
 [ 5 19  6 19]
 [11  5  3  4]]


In [34]:
product = np.dot(a,b)
print(product)

[[143 101  30 169]
 [116  72  18 142]
 [150 128  48 156]]


In [35]:
a = np.random.randint(10, size=(3,3))
b = np.random.randint(20, size=(4,4))
product = np.dot(a,b)
print(product)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

**Element wise multiplication**

In [38]:
a = np.random.randint(10, size=(3,3))
b = np.random.randint(20, size=(3,3))

In [39]:
print(a)

[[3 9 2]
 [5 2 3]
 [2 1 3]]


In [40]:
print(b)

[[19 15 12]
 [10 17  9]
 [19 16  1]]


In [41]:
product = np.multiply(a,b)
print(product)

[[ 57 135  24]
 [ 50  34  27]
 [ 38  16   3]]
