<a href="https://colab.research.google.com/github/Priangshu-18/Matrix-basics/blob/main/Working_with_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
matrix_1 = np.array([[2,3],[6,7]])

In [ ]:
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_2 = np.array([[2,3],[6,7],[8,6]])
print(matrix_2)

[[2 3]
 [6 7]
 [8 6]]


In [4]:
# Random Matrix
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.69786772 0.7782934  0.6766709 ]
 [0.24738588 0.2240557  0.55872986]
 [0.70705468 0.92210165 0.839918  ]]


In [5]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[71  8 41  3 59]
 [54 70 96 60 50]
 [93 33 23 78 60]
 [49 36 86 68 47]]


In [7]:
# Matrix with all values as 1
ones_matrix = np.ones((5,5), dtype=int)
print(ones_matrix)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
